language: python
python:
- '2.7'
- '3.3'
- '3.4'
- '3.5'
- '3.6'
install:
- pip install -r requirements.txt
- cd forge
- pip install .
- cd ..
env:
- TEST_ENV=travis
script:
- travis_wait 30 py.test
before_install:
- openssl aes-256-cbc -K $encrypted_4b438100ad6f_key -iv $encrypted_4b438100ad6f_iv
  -in travis.tar.enc -out travis.tar -d
- tar xvf travis.tar
- mkdir -p ~/mdf/credentials/
- mv MDF_Forge_tokens.json ~/mdf/credentials/MDF_Forge_tokens.json
notifications:
  email:
    recipients:
    - jgaff@uchicago.edu
    on_success: never
    on_failure: always
  slack:
    secure: h9Pn5T7PPIcoKAu61I7/bigL9A3UdvmF+D92mbEGCr1w+Vk9/TaTwayxNleVLd2ukG9cuMKFJ9lYzDamuHkadKVue7SbyXLp7Gg+n88Vdn5OJ0tSgVG/V4E9qj0S8GSGX1XnBdiMpV8tTqf1CAiNvAu7xA4kstd1WooFIostkk6v3lGIGAr5y4F+Ziz4JozRgJWByMSkx46GEFUFazLpVSz0iIZL1J/Jyzh2D0uo52f8V6kWqXJsyJZXKQYLNZD6sQNk48DcAOZoJPkmJ1MTFuoa2Qi0Re9Q0L8A+n2CZ0B+/4IxWIJFkYIIJ3/Amn7/2pks8+dNcmX0zFPgdxiP/L3LW4AMLe3Y1cTWCDKxjHzdpiMs83ZfrApPZqdAu66F/mLY+kNY9xDtlQ5z9UA/AGkVAO9gARWUHwZNEF4NQ1pN3MSwTwhlDnw/SJXgkWa+5wR7RNDAGbLMaWztphxslOCj/5HeDNA/mMBcb2yoTMsZzMdZRloKkaCx+EjVc7bZlBfo1GVB2AgkASc5zAUn+6w8oTARm2oHDMjJc3c3HvO3rbHteC3y89KcnNWIk7q1KuBz/53JyvQFvc5Iil2yFFKcopS5c7B1tP/gTa1CgrOhLidPr1qISWS31X6UA+7GNmVYJl0kUfWNCDLHBkw4PfhUw894BLsTNB9pIICaEBs=
deploy:
  provider: pypi
  user: jgaff
  on:
    tags: true
  distributions: "sdist bdist_wheel"
  password:
    secure: Bao2ot8PG8VX8EjzQ9kgLmzQIkepGf4o3VPM1IhUuYjlos3cpVtCn1Vqn1GLShdJzKXrgkAo12A0qkxt9T0Mx/hwYtkY4mlg/0wTo8DAKq96Gy6kjb9xlXw+DpeoVwHOUkibCRIPd+QC3z5Ut36l/xAR31xJ8BDhIkD7MaVZXwgB2ykG3tElL63peFCMVPhS7HmZ9Hf+11b73MPdlG8j/gNReDtd9vCU/LmGrjiHukB3nQLYmmVnCvbfwQdUJ3t2B9BpNlRUwcfqLOyTFIQoWlo+GkkyhTsafWEhHMQgsZvcti5PPlgbUSrUK1fUc5+/gRRsn6RJ0Bof+njXmgVmgOA4XGRsO+/L4Dfe9gXAleR1lx/lIzkh9hPot870w+65WIQs4tdSx9cShXHx+d6uv3eWkzPhCzWZwrK5DL4M5oXRSpojA8MPzuYsTsWaOdCHXj6g7KymdHRqgi7QPWJGvOf/Gs+xHaLcSKMZz/uLBVFyTCjcy3vyv48n3HljZTLYNp6tpV77Yo5i/qNtQJ7Tb853L/iBosGQd2DMVxGvbJbhu7grdgA5wt/nGOKLNLDYc7AmgSQoWh3un5/c0cTQYQo8e13fLC43FTKTQthsalZNBfLcaCDVJ6KvKMh/kF11pYfTQ8hDzpGsFklthXvu9zggS1I4sHwbYjb6Z7lAle0=
