language: python
python:
- '3.6'
install:
- pip install -r requirements.txt
- pip install mdf_forge
- travis_wait 30 mvn install
script:
- py.test
before_install:
- openssl aes-256-cbc -K $encrypted_4b438100ad6f_key -iv $encrypted_4b438100ad6f_iv
  -in travis.tar.enc -out travis.tar -d
- tar xvf travis.tar
- mkdir -p ~/mdf/credentials/
- mv MDF_Forge_tokens.json ~/mdf/credentials/MDF_Forge_tokens.json
